name: Testes automatizados

on:
  push:
    branches:
      - main
      - dev

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
  
      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r testes/requirements.txt
          pip install requests

      - name: Install Docker Compose
        run: sudo apt install docker-compose

      - name: Pull MySQL image
        run: sudo docker pull mysql/mysql-server:5.7

      - name: Listar imagens Docker
        run: sudo docker images

      - name: Executar contêiner MySQL
        run: |
          sudo docker run --name=mysql -p3306:3306 -e MYSQL_ROOT_PASSWORD=password --restart on-failure -d mysql/mysql-server:5.7
          sleep 30s

      - name: Executar comandos no contêiner MySQL
        run: |
          sudo docker exec mysql mysql -u root -ppassword -e "CREATE USER 'root'@'%' IDENTIFIED BY 'password'; \
          GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; \
          CREATE DATABASE datalogger; \
          FLUSH PRIVILEGES;"

      - name: Criar arquivo .env
        run: |
          echo "PASSWORD=password" >> .env
          echo "DATABASE=datalogger" >> .env

      - name: Instalar dependências Node.js
        run: npm install

      - name: Rodar projeto
        run: nohup npm run dev > /dev/null 2>&1 &

      - name: Aguardar 10 segundos
        run: sleep 10s

      - name: Executar pytest
        run: pytest